### ISSUE TITLE
We need the updated insight-api that works with this android wallet

### ISSUE THREAD

**Issue by denuoweb** [qtumproject/qtum-android#11]
Please give us the updated insight-api that works with this please.

**Comment by KirillVolkov** [comment]
https://github.com/qtumproject/insight-api

**Comment by denuoweb** [comment]
> https://github.com/qtumproject/insight-api

Sorry but this is not what works with qtum-android. Qtum released Mobile-API-Server but now Qtum is missing Server-Receive inorder for that to run.

https://github.com/qtumproject/mobile-api-server
https://github.com/qtumproject/server-receive
