### ISSUE TITLE
error in ui getHistoryList

### ISSUE THREAD

**Issue by denuoweb** [qtumproject/qtum-android#8]
wallet/ui/fragment/wallet_fragment/WalletInteractorImpl.java

    public Observable<HistoryResponse> getHistoryList(int limit, int offest) {
        return HtmlcoinService.newInstance().getHistoryListForSeveralAddresses(getAddresses(), limit, offest);

....................offset is spelled offest

**Comment by KirillVolkov** [comment]
HtmlcoinService?
